// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace Vectool.OaiUI
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.actionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertToDocxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertToMdToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertToPdfToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.getGitChangesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fileSizeSummaryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.runTestsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPageMain = new System.Windows.Forms.TabPage();
            this.lblVectorStoreManagement = new System.Windows.Forms.Label();
            this.comboBoxVectorStores = new System.Windows.Forms.ComboBox();
            this.txtNewVectorStoreName = new System.Windows.Forms.TextBox();
            this.btnCreateNewVectorStore = new System.Windows.Forms.Button();
            this.btnSelectFolders = new System.Windows.Forms.Button();
            this.btnRunTests = new System.Windows.Forms.Button();
            this.listBoxSelectedFolders = new System.Windows.Forms.ListBox();
            this.tabPageSettings = new System.Windows.Forms.TabPage();
            this.lblSettingsVectorStore = new System.Windows.Forms.Label();
            this.cmbSettingsVectorStore = new System.Windows.Forms.ComboBox();
            this.chkInheritExcludedFiles = new System.Windows.Forms.CheckBox();
            this.lblExcludedFiles = new System.Windows.Forms.Label();
            this.txtExcludedFiles = new System.Windows.Forms.TextBox();
            this.chkInheritExcludedFolders = new System.Windows.Forms.CheckBox();
            this.lblExcludedFolders = new System.Windows.Forms.Label();
            this.txtExcludedFolders = new System.Windows.Forms.TextBox();
            this.btnSaveVsSettings = new System.Windows.Forms.Button();
            this.tabPageRecentFiles = new System.Windows.Forms.TabPage();
            this.recentFilesPanel = new oaiUI.RecentFiles.RecentFilesPanel();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.statusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.progressBar = new System.Windows.Forms.ToolStripProgressBar();
            this.menuStrip1.SuspendLayout();
            this.statusStrip1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabPageMain.SuspendLayout();
            this.tabPageSettings.SuspendLayout();
            this.tabPageRecentFiles.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.actionsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1200, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.F4)));
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(135, 22);
            this.exitToolStripMenuItem.Text = "Exit";
            // 
            // actionsToolStripMenuItem
            // 
            this.actionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.convertToDocxToolStripMenuItem,
            this.convertToMdToolStripMenuItem,
            this.convertToPdfToolStripMenuItem,
            this.toolStripSeparator1,
            this.getGitChangesToolStripMenuItem,
            this.fileSizeSummaryToolStripMenuItem,
            this.runTestsToolStripMenuItem});
            this.actionsToolStripMenuItem.Name = "actionsToolStripMenuItem";
            this.actionsToolStripMenuItem.Size = new System.Drawing.Size(59, 20);
            this.actionsToolStripMenuItem.Text = "Actions";
            // 
            // convertToDocxToolStripMenuItem
            // 
            this.convertToDocxToolStripMenuItem.Name = "convertToDocxToolStripMenuItem";
            this.convertToDocxToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D)));
            this.convertToDocxToolStripMenuItem.Size = new System.Drawing.Size(220, 22);
            this.convertToDocxToolStripMenuItem.Text = "Convert to DOCX";
            // 
            // convertToMdToolStripMenuItem
            // 
            this.convertToMdToolStripMenuItem.Name = "convertToMdToolStripMenuItem";
            this.convertToMdToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.M)));
            this.convertToMdToolStripMenuItem.Size = new System.Drawing.Size(220, 22);
            this.convertToMdToolStripMenuItem.Text = "Convert to MD";
            // 
            // convertToPdfToolStripMenuItem
            // 
            this.convertToPdfToolStripMenuItem.Name = "convertToPdfToolStripMenuItem";
            this.convertToPdfToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.P)));
            this.convertToPdfToolStripMenuItem.Size = new System.Drawing.Size(220, 22);
            this.convertToPdfToolStripMenuItem.Text = "Convert to PDF";
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(217, 6);
            // 
            // getGitChangesToolStripMenuItem
            // 
            this.getGitChangesToolStripMenuItem.Name = "getGitChangesToolStripMenuItem";
            this.getGitChangesToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.G)));
            this.getGitChangesToolStripMenuItem.Size = new System.Drawing.Size(220, 22);
            this.getGitChangesToolStripMenuItem.Text = "Get Git Changes";
            // 
            // fileSizeSummaryToolStripMenuItem
            // 
            this.fileSizeSummaryToolStripMenuItem.Name = "fileSizeSummaryToolStripMenuItem";
            this.fileSizeSummaryToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F)));
            this.fileSizeSummaryToolStripMenuItem.Size = new System.Drawing.Size(220, 22);
            this.fileSizeSummaryToolStripMenuItem.Text = "File Size Summary";
            // 
            // runTestsToolStripMenuItem
            // 
            this.runTestsToolStripMenuItem.Name = "runTestsToolStripMenuItem";
            this.runTestsToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.T)));
            this.runTestsToolStripMenuItem.Size = new System.Drawing.Size(220, 22);
            this.runTestsToolStripMenuItem.Text = "Run Tests";
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPageMain);
            this.tabControl1.Controls.Add(this.tabPageSettings);
            this.tabControl1.Controls.Add(this.tabPageRecentFiles);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 24);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1200, 626);
            this.tabControl1.TabIndex = 1;
            // 
            // tabPageMain
            // 
            this.tabPageMain.Controls.Add(this.lblVectorStoreManagement);
            this.tabPageMain.Controls.Add(this.comboBoxVectorStores);
            this.tabPageMain.Controls.Add(this.txtNewVectorStoreName);
            this.tabPageMain.Controls.Add(this.btnCreateNewVectorStore);
            this.tabPageMain.Controls.Add(this.btnSelectFolders);
            this.tabPageMain.Controls.Add(this.btnRunTests);
            this.tabPageMain.Controls.Add(this.listBoxSelectedFolders);
            this.tabPageMain.Location = new System.Drawing.Point(4, 24);
            this.tabPageMain.Name = "tabPageMain";
            this.tabPageMain.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageMain.Size = new System.Drawing.Size(1192, 598);
            this.tabPageMain.TabIndex = 0;
            this.tabPageMain.Text = "Main";
            this.tabPageMain.UseVisualStyleBackColor = true;
            // 
            // lblVectorStoreManagement
            // 
            this.lblVectorStoreManagement.AutoSize = true;
            this.lblVectorStoreManagement.Location = new System.Drawing.Point(20, 20);
            this.lblVectorStoreManagement.Name = "lblVectorStoreManagement";
            this.lblVectorStoreManagement.Size = new System.Drawing.Size(169, 15);
            this.lblVectorStoreManagement.TabIndex = 0;
            this.lblVectorStoreManagement.Text = "Select or Create Vector Store";
            // 
            // comboBoxVectorStores
            // 
            this.comboBoxVectorStores.FormattingEnabled = true;
            this.comboBoxVectorStores.Location = new System.Drawing.Point(20, 45);
            this.comboBoxVectorStores.Name = "comboBoxVectorStores";
            this.comboBoxVectorStores.Size = new System.Drawing.Size(350, 23);
            this.comboBoxVectorStores.TabIndex = 1;
            // 
            // txtNewVectorStoreName
            // 
            this.txtNewVectorStoreName.Location = new System.Drawing.Point(390, 45);
            this.txtNewVectorStoreName.Name = "txtNewVectorStoreName";
            this.txtNewVectorStoreName.PlaceholderText = "New vector store name...";
            this.txtNewVectorStoreName.Size = new System.Drawing.Size(200, 23);
            this.txtNewVectorStoreName.TabIndex = 2;
            // 
            // btnCreateNewVectorStore
            // 
            this.btnCreateNewVectorStore.Location = new System.Drawing.Point(600, 43);
            this.btnCreateNewVectorStore.Name = "btnCreateNewVectorStore";
            this.btnCreateNewVectorStore.Size = new System.Drawing.Size(100, 27);
            this.btnCreateNewVectorStore.TabIndex = 3;
            this.btnCreateNewVectorStore.Text = "Create New";
            this.btnCreateNewVectorStore.UseVisualStyleBackColor = true;
            // 
            // btnSelectFolders
            // 
            this.btnSelectFolders.Location = new System.Drawing.Point(20, 85);
            this.btnSelectFolders.Name = "btnSelectFolders";
            this.btnSelectFolders.Size = new System.Drawing.Size(150, 30);
            this.btnSelectFolders.TabIndex = 4;
            this.btnSelectFolders.Text = "Select Folders...";
            this.btnSelectFolders.UseVisualStyleBackColor = true;
            // 
            // btnRunTests
            // 
            this.btnRunTests.Location = new System.Drawing.Point(190, 85);
            this.btnRunTests.Name = "btnRunTests";
            this.btnRunTests.Size = new System.Drawing.Size(150, 30);
            this.btnRunTests.TabIndex = 5;
            this.btnRunTests.Text = "Run Tests";
            this.btnRunTests.UseVisualStyleBackColor = true;
            // 
            // listBoxSelectedFolders
            // 
            this.listBoxSelectedFolders.FormattingEnabled = true;
            this.listBoxSelectedFolders.ItemHeight = 15;
            this.listBoxSelectedFolders.Location = new System.Drawing.Point(20, 125);
            this.listBoxSelectedFolders.Name = "listBoxSelectedFolders";
            this.listBoxSelectedFolders.Size = new System.Drawing.Size(600, 400);
            this.listBoxSelectedFolders.TabIndex = 6;
            // 
            // tabPageSettings
            // 
            this.tabPageSettings.Controls.Add(this.lblSettingsVectorStore);
            this.tabPageSettings.Controls.Add(this.cmbSettingsVectorStore);
            this.tabPageSettings.Controls.Add(this.chkInheritExcludedFiles);
            this.tabPageSettings.Controls.Add(this.lblExcludedFiles);
            this.tabPageSettings.Controls.Add(this.txtExcludedFiles);
            this.tabPageSettings.Controls.Add(this.chkInheritExcludedFolders);
            this.tabPageSettings.Controls.Add(this.lblExcludedFolders);
            this.tabPageSettings.Controls.Add(this.txtExcludedFolders);
            this.tabPageSettings.Controls.Add(this.btnSaveVsSettings);
            this.tabPageSettings.Location = new System.Drawing.Point(4, 24);
            this.tabPageSettings.Name = "tabPageSettings";
            this.tabPageSettings.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageSettings.Size = new System.Drawing.Size(1192, 598);
            this.tabPageSettings.TabIndex = 1;
            this.tabPageSettings.Text = "Settings";
            this.tabPageSettings.UseVisualStyleBackColor = true;
            // 
            // lblSettingsVectorStore
            // 
            this.lblSettingsVectorStore.AutoSize = true;
            this.lblSettingsVectorStore.Location = new System.Drawing.Point(20, 20);
            this.lblSettingsVectorStore.Name = "lblSettingsVectorStore";
            this.lblSettingsVectorStore.Size = new System.Drawing.Size(74, 15);
            this.lblSettingsVectorStore.TabIndex = 0;
            this.lblSettingsVectorStore.Text = "Vector Store";
            // 
            // cmbSettingsVectorStore
            // 
            this.cmbSettingsVectorStore.FormattingEnabled = true;
            this.cmbSettingsVectorStore.Location = new System.Drawing.Point(20, 40);
            this.cmbSettingsVectorStore.Name = "cmbSettingsVectorStore";
            this.cmbSettingsVectorStore.Size = new System.Drawing.Size(350, 23);
            this.cmbSettingsVectorStore.TabIndex = 1;
            // 
            // chkInheritExcludedFiles
            // 
            this.chkInheritExcludedFiles.AutoSize = true;
            this.chkInheritExcludedFiles.Location = new System.Drawing.Point(20, 80);
            this.chkInheritExcludedFiles.Name = "chkInheritExcludedFiles";
            this.chkInheritExcludedFiles.Size = new System.Drawing.Size(168, 19);
            this.chkInheritExcludedFiles.TabIndex = 2;
            this.chkInheritExcludedFiles.Text = "Inherit Global Excluded Files";
            this.chkInheritExcludedFiles.UseVisualStyleBackColor = true;
            // 
            // lblExcludedFiles
            // 
            this.lblExcludedFiles.AutoSize = true;
            this.lblExcludedFiles.Location = new System.Drawing.Point(20, 110);
            this.lblExcludedFiles.Name = "lblExcludedFiles";
            this.lblExcludedFiles.Size = new System.Drawing.Size(160, 15);
            this.lblExcludedFiles.TabIndex = 3;
            this.lblExcludedFiles.Text = "Excluded Files (one per line)";
            // 
            // txtExcludedFiles
            // 
            this.txtExcludedFiles.Location = new System.Drawing.Point(20, 130);
            this.txtExcludedFiles.Multiline = true;
            this.txtExcludedFiles.Name = "txtExcludedFiles";
            this.txtExcludedFiles.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtExcludedFiles.Size = new System.Drawing.Size(500, 120);
            this.txtExcludedFiles.TabIndex = 4;
            // 
            // chkInheritExcludedFolders
            // 
            this.chkInheritExcludedFolders.AutoSize = true;
            this.chkInheritExcludedFolders.Location = new System.Drawing.Point(20, 270);
            this.chkInheritExcludedFolders.Name = "chkInheritExcludedFolders";
            this.chkInheritExcludedFolders.Size = new System.Drawing.Size(183, 19);
            this.chkInheritExcludedFolders.TabIndex = 5;
            this.chkInheritExcludedFolders.Text = "Inherit Global Excluded Folders";
            this.chkInheritExcludedFolders.UseVisualStyleBackColor = true;
            // 
            // lblExcludedFolders
            // 
            this.lblExcludedFolders.AutoSize = true;
            this.lblExcludedFolders.Location = new System.Drawing.Point(20, 300);
            this.lblExcludedFolders.Name = "lblExcludedFolders";
            this.lblExcludedFolders.Size = new System.Drawing.Size(177, 15);
            this.lblExcludedFolders.TabIndex = 6;
            this.lblExcludedFolders.Text = "Excluded Folders (one per line)";
            // 
            // txtExcludedFolders
            // 
            this.txtExcludedFolders.Location = new System.Drawing.Point(20, 320);
            this.txtExcludedFolders.Multiline = true;
            this.txtExcludedFolders.Name = "txtExcludedFolders";
            this.txtExcludedFolders.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtExcludedFolders.Size = new System.Drawing.Size(500, 120);
            this.txtExcludedFolders.TabIndex = 7;
            // 
            // btnSaveVsSettings
            // 
            this.btnSaveVsSettings.Location = new System.Drawing.Point(20, 460);
            this.btnSaveVsSettings.Name = "btnSaveVsSettings";
            this.btnSaveVsSettings.Size = new System.Drawing.Size(150, 30);
            this.btnSaveVsSettings.TabIndex = 8;
            this.btnSaveVsSettings.Text = "Save Settings";
            this.btnSaveVsSettings.UseVisualStyleBackColor = true;
            // 
            // tabPageRecentFiles
            // 
            this.tabPageRecentFiles.Controls.Add(this.recentFilesPanel);
            this.tabPageRecentFiles.Location = new System.Drawing.Point(4, 24);
            this.tabPageRecentFiles.Name = "tabPageRecentFiles";
            this.tabPageRecentFiles.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageRecentFiles.Size = new System.Drawing.Size(1192, 598);
            this.tabPageRecentFiles.TabIndex = 2;
            this.tabPageRecentFiles.Text = "Recent Files";
            this.tabPageRecentFiles.UseVisualStyleBackColor = true;
            // 
            // recentFilesPanel
            // 
            this.recentFilesPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.recentFilesPanel.Location = new System.Drawing.Point(3, 3);
            this.recentFilesPanel.Name = "recentFilesPanel";
            this.recentFilesPanel.Size = new System.Drawing.Size(1186, 592);
            this.recentFilesPanel.TabIndex = 0;
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.statusLabel,
            this.progressBar});
            this.statusStrip1.Location = new System.Drawing.Point(0, 650);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(1200, 22);
            this.statusStrip1.TabIndex = 2;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // statusLabel
            // 
            this.statusLabel.Name = "statusLabel";
            this.statusLabel.Size = new System.Drawing.Size(39, 17);
            this.statusLabel.Text = "Ready";
            // 
            // progressBar
            // 
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(200, 16);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 672);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "VecTool";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.tabPageMain.ResumeLayout(false);
            this.tabPageMain.PerformLayout();
            this.tabPageSettings.ResumeLayout(false);
            this.tabPageSettings.PerformLayout();
            this.tabPageRecentFiles.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        // MenuStrip and menu items
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem actionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertToDocxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertToMdToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertToPdfToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem getGitChangesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileSizeSummaryToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem runTestsToolStripMenuItem;

        // TabControl and tabs
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPageMain;
        private System.Windows.Forms.TabPage tabPageSettings;
        private System.Windows.Forms.TabPage tabPageRecentFiles;

        // Main Tab controls
        private System.Windows.Forms.Label lblVectorStoreManagement;
        private System.Windows.Forms.ComboBox comboBoxVectorStores;
        private System.Windows.Forms.TextBox txtNewVectorStoreName;
        private System.Windows.Forms.Button btnCreateNewVectorStore;
        private System.Windows.Forms.Button btnSelectFolders;
        private System.Windows.Forms.Button btnRunTests;
        private System.Windows.Forms.ListBox listBoxSelectedFolders;

        // Settings Tab controls
        private System.Windows.Forms.Label lblSettingsVectorStore;
        private System.Windows.Forms.ComboBox cmbSettingsVectorStore;
        private System.Windows.Forms.CheckBox chkInheritExcludedFiles;
        private System.Windows.Forms.Label lblExcludedFiles;
        private System.Windows.Forms.TextBox txtExcludedFiles;
        private System.Windows.Forms.CheckBox chkInheritExcludedFolders;
        private System.Windows.Forms.Label lblExcludedFolders;
        private System.Windows.Forms.TextBox txtExcludedFolders;
        private System.Windows.Forms.Button btnSaveVsSettings;

        // Recent Files Tab
        private oaiUI.RecentFiles.RecentFilesPanel recentFilesPanel;

        // StatusStrip
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel statusLabel;
        private System.Windows.Forms.ToolStripProgressBar progressBar;
    }
}
