//
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//
namespace Vectool.OaiUI
{
    partial class MainForm
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        //   the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();

            // Menu initialization
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.actionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertToDocxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertToMdToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.convertToPdfToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.getGitChangesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fileSizeSummaryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.runTestsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();

            // Other controls
            this.cmbSettingsVectorStore = new System.Windows.Forms.ComboBox();
            this.txtExcludedFiles = new System.Windows.Forms.TextBox();
            this.txtExcludedFolders = new System.Windows.Forms.TextBox();
            this.chkInheritExcludedFiles = new System.Windows.Forms.CheckBox();
            this.chkInheritExcludedFolders = new System.Windows.Forms.CheckBox();
            this.btnRunTests = new System.Windows.Forms.Button();
            this.btnSaveVsSettings = new System.Windows.Forms.Button();
            this.comboBoxVectorStores = new System.Windows.Forms.ComboBox();

            // Configure MenuStrip (copy from your plan document)
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        this.fileToolStripMenuItem,
        this.actionsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(800, 24);
            this.menuStrip1.TabIndex = 0;

            // File menu
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Text = "File";

            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.F4)));
            this.exitToolStripMenuItem.Text = "Exit";

            // Actions menu
            this.actionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        this.convertToDocxToolStripMenuItem,
        this.convertToMdToolStripMenuItem,
        this.convertToPdfToolStripMenuItem,
        this.toolStripSeparator1,
        this.getGitChangesToolStripMenuItem,
        this.fileSizeSummaryToolStripMenuItem,
        this.runTestsToolStripMenuItem});
            this.actionsToolStripMenuItem.Name = "actionsToolStripMenuItem";
            this.actionsToolStripMenuItem.Text = "Actions";

            // Individual action items
            this.convertToDocxToolStripMenuItem.Name = "convertToDocxToolStripMenuItem";
            this.convertToDocxToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D)));
            this.convertToDocxToolStripMenuItem.Text = "Convert to DOCX";

            this.convertToMdToolStripMenuItem.Name = "convertToMdToolStripMenuItem";
            this.convertToMdToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.M)));
            this.convertToMdToolStripMenuItem.Text = "Convert to MD";

            this.convertToPdfToolStripMenuItem.Name = "convertToPdfToolStripMenuItem";
            this.convertToPdfToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.P)));
            this.convertToPdfToolStripMenuItem.Text = "Convert to PDF";

            this.getGitChangesToolStripMenuItem.Name = "getGitChangesToolStripMenuItem";
            this.getGitChangesToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.G)));
            this.getGitChangesToolStripMenuItem.Text = "Get Git Changes";

            this.fileSizeSummaryToolStripMenuItem.Name = "fileSizeSummaryToolStripMenuItem";
            this.fileSizeSummaryToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F)));
            this.fileSizeSummaryToolStripMenuItem.Text = "File Size Summary";

            this.runTestsToolStripMenuItem.Name = "runTestsToolStripMenuItem";
            this.runTestsToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.T)));
            this.runTestsToolStripMenuItem.Text = "Run Tests";

            this.toolStripSeparator1.Name = "toolStripSeparator1";

            // MainForm
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.MainMenuStrip = this.menuStrip1;
            this.Controls.Add(this.menuStrip1);
            this.Text = "MainForm";
        }
        #endregion

        // Manually added field declarations
        private System.Windows.Forms.ComboBox cmbSettingsVectorStore;
        private System.Windows.Forms.TextBox txtExcludedFiles;
        private System.Windows.Forms.TextBox txtExcludedFolders;
        private System.Windows.Forms.CheckBox chkInheritExcludedFiles;
        private System.Windows.Forms.CheckBox chkInheritExcludedFolders;
        private System.Windows.Forms.Button btnRunTests;
        private System.Windows.Forms.Button btnSaveVsSettings;  // ADDED
        private System.Windows.Forms.ComboBox comboBoxVectorStores;

        // Menu items - ADD THESE
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem actionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem runTestsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem getGitChangesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileSizeSummaryToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertToDocxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertToMdToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem convertToPdfToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
    }
}

