using VecTool.Handlers.Traversal;

namespace UnitTests.Traversal
{
    using NLog;
    using NLog.Config;
    using NLog.Targets;
    using NUnit.Framework;
    using Shouldly;
    using System;
    using System.IO;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// Comprehensive unit tests for FileMarkerExtractor (Layer 2 file marker extraction). Covers valid markers,
    /// XSD/JSON specifics, boundary conditions, encoding, and error handling. Uses NUnit + Shouldly with LogCtx audit
    /// trail verification.
    /// </summary>
    [TestFixture]
    public class FileMarkerExtractorTests
    {
        private FileMarkerExtractor extractor = null!;
        private string testRootDirectory = null!;

        [SetUp]
        public void Setup()
        {
            // Arrange - Initialize test directory
            testRootDirectory = Path.Combine(
                Path.GetTempPath(),
                "FileMarkerExtractorTests",
                Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(testRootDirectory);

            // Create extractor instance
            extractor = new FileMarkerExtractor();
        }

        [TearDown]
        public void TearDown()
        {
            // Cleanup
            LogManager.Flush();
            if(Directory.Exists(testRootDirectory))
            {
                Directory.Delete(testRootDirectory, recursive: true);
            }
        }

        #region Valid Marker Extraction (5 tests)

        /// <summary>
        /// Test 1: Extract marker from C# file with standard comment syntax. Pattern: // VECTOOL_EXCLUDE reason
        /// @SpaceReference
        /// </summary>
        [Test]
        public void ExtractMarker_WithValidCSharpMarker_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"// [VECTOOL:EXCLUDE:generated_by_xsd@XSD-Schema-Docs]
namespace Generated
{
    public class AutoGenerated { }
}";
            var filePath = Path.Combine(testRootDirectory, "Generated.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.FilePath.ShouldBe(filePath);
            result.Reason.ShouldBe("generated_by_xsd", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@XSD-Schema-Docs");
            result.LineNumber.ShouldBe(1);
            result.ExtractedAt.ShouldBeGreaterThan(DateTime.UtcNow.AddSeconds(-5));

            // Verify audit trail in LogCtx
            //var logs = memoryTarget.Logs.ToList();
            //logs.Any(l => l.Contains("File marker extracted successfully")).ShouldBeTrue();
            //logs.Any(l => l.Contains("XSD-Schema-Docs")).ShouldBeTrue();
        }

        /// <summary>
        /// Test 2: Extract marker from Python file with hash comment syntax. Pattern: # VECTOOL_EXCLUDE reason
        /// @Reference
        /// </summary>
        [Test]
        public void ExtractMarker_WithPythonMarker_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"# [VECTOOL:EXCLUDE:vendor_library@AI-Generated]
# This file is auto-generated
import generated_code
";
            var filePath = Path.Combine(testRootDirectory, "generated_module.py");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("vendor_library", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@AI-Generated");
            result.LineNumber.ShouldBe(1);
        }

        /// <summary>
        /// Test 3: Extract marker from XML/XAML file with XML comment syntax. Pattern: &lt;!-- VECTOOL_EXCLUDE reason
        /// @Reference --&gt;
        /// </summary>
        [Test]
        public void ExtractMarker_WithXmlMarker_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"<!-- [VECTOOL:EXCLUDE:generated_by_tool@XML-Generator] -->
<?xml version=""1.0"" encoding=""utf-8""?>
<Configuration></Configuration>";
            var filePath = Path.Combine(testRootDirectory, "config.xml");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("generated_by_tool", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@XML-Generator");
        }

        /// <summary>
        /// Test 4: Extract marker from JSON file with vectool_exclude string. NEW - JSON string-embedded marker:
        /// "vectool_exclude": "reason @Reference" Must appear in first 50 lines and 1500 bytes.
        /// </summary>
        [Test]
        public void ExtractMarker_WithJsonMarker_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"{
  ""vectool_exclude"": ""[VECTOOL:EXCLUDE:generated_by_tool@JSON-Schema]"",
  ""name"": ""GeneratedConfig"",
  ""version"": ""1.0.0""
}";
            var filePath = Path.Combine(testRootDirectory, "config.json");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("generated_by_tool", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@JSON-Schema");
            result.LineNumber.ShouldBe(2);
        }

        /// <summary>
        /// Test 5: Marker with missing optional SpaceReference defaults to null. Pattern: // VECTOOL_EXCLUDE reason (no
        /// @Reference)
        /// </summary>
        [Test]
        public void ExtractMarker_WithOptionalSpaceReference_ReturnsNull()
        {
            // Arrange - Marker without optional reference
            var content = @"// [VECTOOL:EXCLUDE:generated_by_xsd]
namespace Generated { }";
            var filePath = Path.Combine(testRootDirectory, "NoRef.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("generated_by_xsd", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBeEmpty();
            result.LineNumber.ShouldBe(1);
        }
        #endregion

        #region XSD-Specific Tests (3 tests) - MANDATORY

        /// <summary>
        /// Test 6: Extract marker from .xsd XML Schema file. XSD files are text-based XML with comment-style markers.
        /// Pattern: &lt;!-- VECTOOL_EXCLUDE generated_by_xsd @XSD-Schema-Docs --&gt;
        /// </summary>
        [Test]
        public void ExtractMarker_FromXsdSchemaFile_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"<!-- [VECTOOL:EXCLUDE:generated_by_xsd@XSD-Schema-Docs] -->
<?xml version=""1.0"" encoding=""UTF-8""?>
<xs:schema xmlns:xs=""http://www.w3.org/2001/XMLSchema"">
  <xs:element name=""Root"" type=""xs:string""/>
</xs:schema>";
            var filePath = Path.Combine(testRootDirectory, "schema.xsd");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.FilePath.ShouldEndWith(".xsd");
            result.Reason.ShouldBe("generated_by_xsd", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@XSD-Schema-Docs");
            result.LineNumber.ShouldBe(1);
        }

        /// <summary>
        /// Test 7: Extract marker from .g.cs generated C# file (XSD-generated code). Generated code files use standard
        /// C# comment syntax. Pattern: // VECTOOL_EXCLUDE generated_by_xsd
        /// </summary>
        [Test]
        public void ExtractMarker_FromXsdGeneratedCsFile_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"// [VECTOOL:EXCLUDE:generated_by_xsd@XSD-Generator]
// <auto-generated>
// This code is generated by XSD.exe
// </auto-generated>
namespace Generated
{
    public class AutoGenClass { }
}";
            var filePath = Path.Combine(testRootDirectory, "AutoGen.g.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.FilePath.ShouldEndWith(".g.cs");
            result.Reason.ShouldBe("generated_by_xsd", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@XSD-Generator");
        }

        /// <summary>
        /// Test 8: Recognize System.CodeDom.Compiler.GeneratedCodeAttribute pattern. Files with [GeneratedCode]
        /// attribute are candidates for exclusion. Pattern: [GeneratedCode("tool", "version")] with VECTOOL_EXCLUDE
        /// marker
        /// </summary>
        [Test]
        public void ExtractMarker_WithGeneratedCodeAttribute_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"// [VECTOOL:EXCLUDE:generated_by_tool@Auto-Generated]
using System.CodeDom.Compiler;

[GeneratedCode(""XSD"", ""2.0"")]
public partial class GeneratedClass
{
    public string Property { get; set; }
}";
            var filePath = Path.Combine(testRootDirectory, "Generated.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("generated_by_tool", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@Auto-Generated");
        }
        #endregion

        #region JSON-Specific Tests (3 tests) - MANDATORY

        /// <summary>
        /// Test 9: Extract marker from JSON using "vectool_exclude" string property. NEW - JSON string support:
        /// "vectool_exclude": "reason @Reference" Must appear within first 50 lines.
        /// </summary>
        [Test]
        public void ExtractMarker_FromJsonWithVectoolExcludeString_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"{
  ""vectool_exclude"": ""[VECTOOL:EXCLUDE:generated_by_tool@JSON-Config]"",
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""title"": ""Configuration"",
  ""type"": ""object"",
  ""properties"": {
    ""name"": { ""type"": ""string"" },
    ""version"": { ""type"": ""string"" }
  }
}";
            var filePath = Path.Combine(testRootDirectory, "schema.json");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("generated_by_tool", StringCompareShould.IgnoreCase);
            result.SpaceReference.ShouldBe("@JSON-Config");
            result.LineNumber.ShouldBe(2);
        }

        /// <summary>
        /// Test 10: JSON file without "vectool_exclude" returns null. Ensures no false positives when marker is absent.
        /// </summary>
        [Test]
        public void ExtractMarker_FromJsonWithoutVectoolExclude_ReturnsNull()
        {
            // Arrange
            var content = @"{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""title"": ""MyConfig"",
  ""type"": ""object""
}";
            var filePath = Path.Combine(testRootDirectory, "config_no_marker.json");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldBeNull();
        }

        /// <summary>
        /// Test 11: JSON marker beyond 50 lines is ignored. Markers must be in file header (first 50 lines, first 1500
        /// bytes).
        /// </summary>
        [Test]
        public void ExtractMarker_FromJsonVectoolExcludeNotFirstFiftyLines_ReturnsNull()
        {
            // Arrange - Create JSON with marker on line 52
            var lines = new StringBuilder();
            for(int i = 1; i <= 51; i++)
            {
                lines.AppendLine($"  \"prop{i}\": \"value{i}\",");
            }
            lines.AppendLine(@"  ""vectool_exclude"": ""generated_by_tool @JSON-Beyond-Limit""");
            var content = "{\n" + lines.ToString() + "\n}";

            var filePath = Path.Combine(testRootDirectory, "large_json.json");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldBeNull("Marker beyond 50 lines should be ignored");
        }
        #endregion

        #region Boundary Conditions (4 tests)

        /// <summary>
        /// Test 12: Marker at exactly line 50 boundary is extracted.
        /// </summary>
        [Test]
        public void ExtractMarker_At50LineBoundary_ReturnsMarkerPattern()
        {
            // Arrange
            var lines = new StringBuilder();
            for(int i = 1; i < 30; i++)
            {
                lines.AppendLine("// Comment line " + i);
            }
            lines.AppendLine("// [VECTOOL:EXCLUDE:boundary_test@Line50]");

            var filePath = Path.Combine(testRootDirectory, "boundary50.cs");
            File.WriteAllText(filePath, lines.ToString());

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.LineNumber.ShouldBe(30);
            result.Reason.ShouldBe("boundary_test", StringCompareShould.IgnoreCase);
        }

        /// <summary>
        /// Test 13: Marker beyond 50 lines is ignored.
        /// </summary>
        [Test]
        public void ExtractMarker_Beyond50Lines_ReturnsNull()
        {
            // Arrange
            var lines = new StringBuilder();
            for(int i = 1; i <= 51; i++)
            {
                lines.AppendLine("// Comment line " + i);
            }
            lines.AppendLine("// VECTOOL_EXCLUDE beyond_50 @Beyond-Limit");

            var filePath = Path.Combine(testRootDirectory, "beyond50.cs");
            File.WriteAllText(filePath, lines.ToString());

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldBeNull();
        }

        /// <summary>
        /// Test 14: Marker at 1500 byte boundary is extracted.
        /// </summary>
        [Test]
        public void ExtractMarker_At1500ByteBoundary_ReturnsMarkerPattern()
        {
            // Arrange - Create content exactly around 1500 bytes with marker just before cutoff
            var content = new StringBuilder();
            content.AppendLine("// [VECTOOL:EXCLUDE:byte_boundary@1500-Bytes]");
            // Pad to near 1500 bytes
            var padding = new string('/', 1400);
            content.AppendLine(padding);

            var filePath = Path.Combine(testRootDirectory, "byte_boundary.cs");
            File.WriteAllText(filePath, content.ToString());

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("byte_boundary", StringCompareShould.IgnoreCase);
        }

        /// <summary>
        /// Test 15: Marker beyond 1500 bytes is ignored.
        /// </summary>
        [Test]
        public void ExtractMarker_Beyond1500Bytes_ReturnsNull()
        {
            // Arrange - Create content > 1500 bytes with marker beyond cutoff
            var content = new StringBuilder();
            var padding = new string('/', 1600);
            content.AppendLine(padding);
            content.AppendLine("// [VECTOOL:EXCLUDE:beyond_bytes@Beyond-1500]");

            var filePath = Path.Combine(testRootDirectory, "beyond1500.cs");
            File.WriteAllText(filePath, content.ToString());

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldBeNull();
        }
        #endregion

        #region Encoding & Edge Cases (4 tests)

        /// <summary>
        /// Test 16: Marker extracted correctly from UTF-8 file with BOM.
        /// </summary>
        [Test]
        public void ExtractMarker_WithUtf8Bom_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"// [VECTOOL:EXCLUDE:utf8_test@UTF8-BOM]
namespace Test { }";
            var filePath = Path.Combine(testRootDirectory, "utf8bom.cs");
            File.WriteAllText(filePath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("utf8_test", StringCompareShould.IgnoreCase);
        }

        /// <summary>
        /// Test 17: Marker extracted from file with mixed line endings (CRLF/LF).
        /// </summary>
        [Test]
        public void ExtractMarker_WithMixedLineEndings_ReturnsMarkerPattern()
        {
            // Arrange - Mix CRLF and LF line endings
            var content = "// [VECTOOL:EXCLUDE:mixed_endings@Mixed-LF-CRLF]\r\nnamespace Test\n{\n    // Comment\r\n}";
            var filePath = Path.Combine(testRootDirectory, "mixed_endings.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("mixed_endings", StringCompareShould.IgnoreCase);
        }

        /// <summary>
        /// Test 18: Header reading performance - extracts within 1ms for typical files.
        /// </summary>
        [Test]
        public void ExtractMarker_WithLargeHeader_PerformsUnder1ms()
        {
            // Arrange - Create large header with marker near start
            var content = new StringBuilder();
            content.AppendLine("// [VECTOOL:EXCLUDE:perf_test@Performance]");
            for(int i = 0; i < 500; i++)
            {
                content.AppendLine("// Comment line " + i);
            }
            content.AppendLine("namespace Test { }");

            var filePath = Path.Combine(testRootDirectory, "large_header.cs");
            File.WriteAllText(filePath, content.ToString());

            // Act
            var stopwatch = System.Diagnostics.Stopwatch.StartNew();
            var result = extractor.ExtractMarker(filePath);
            stopwatch.Stop();
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            stopwatch.ElapsedMilliseconds.ShouldBeLessThan(100, "Extraction should complete quickly");
        }

        /// <summary>
        /// Test 19: Empty file returns null without errors.
        /// </summary>
        [Test]
        public void ExtractMarker_WithEmptyFile_ReturnsNull()
        {
            // Arrange
            var filePath = Path.Combine(testRootDirectory, "empty.cs");
            File.WriteAllText(filePath, string.Empty);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldBeNull();
        }
        #endregion

        #region LogError Handling (3 tests)

        /// <summary>
        /// Test 20: Non-existent file returns null with warning logged (no exception).
        /// </summary>
        [Test]
        public void ExtractMarker_WithNonExistentFile_ReturnsNullAndLogsWarning()
        {
            // Arrange
            var nonExistentPath = Path.Combine(testRootDirectory, "does_not_exist.cs");

            // Act
            var result = extractor.ExtractMarker(nonExistentPath);
            LogManager.Flush();

            // Assert
            result.ShouldBeNull();
        }

        /// <summary>
        /// Test 21: File without read permission returns null with warning. (Platform-dependent; may be skipped on
        /// systems without permission control)
        /// </summary>
        [Test]
        [Platform(Include = "Win,Linux")]
        public void ExtractMarker_WithFileReadPermissionDenied_ReturnsNull()
        {
            // Arrange
            var filePath = Path.Combine(testRootDirectory, "no_permission.cs");
            File.WriteAllText(filePath, "// content");

            try
            {
                // Remove read permissions
                var fileInfo = new FileInfo(filePath);
                var security = fileInfo.GetAccessControl();
                security.SetAccessRuleProtection(isProtected: true, preserveInheritance: false);
                fileInfo.SetAccessControl(security);


                // Act
                var result = extractor.ExtractMarker(filePath);
                LogManager.Flush();

                // Assert
                result.ShouldBeNull();
            } finally
            {
                // Cleanup - restore permissions
                try
                {
                    var fileInfo = new FileInfo(filePath);
                    var security = fileInfo.GetAccessControl();
                    security.SetAccessRuleProtection(isProtected: false, preserveInheritance: true);
                    fileInfo.SetAccessControl(security);
                } catch
                { /* ignored */
                }
            }
        }

        /// <summary>
        /// Test 22: Regex timeout during pattern matching logs warning and returns null. Simulated by testing with very
        /// complex input pattern (if applicable).
        /// </summary>
        [Test]
        public void ExtractMarker_WithRegexTimeout_ReturnsNull()
        {
            // Arrange - Create pathologically complex content (worst-case for regex)
            var complexPattern = string.Concat(Enumerable.Repeat("a", 1000)) + "VECTOOL_EXCLUDE";
            var filePath = Path.Combine(testRootDirectory, "regex_stress.txt");
            File.WriteAllText(filePath, complexPattern);

            // Act - Should timeout gracefully or return null
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert - Either null (timeout caught) or valid result (pattern matched despite complexity)
            // Should NOT throw RegexMatchTimeoutException
            (result == null || result is FileMarkerPattern).ShouldBeTrue();
        }
        #endregion

        #region Case-Insensitivity Tests (Bonus)

        /// <summary>
        /// Test 23: Marker pattern matching is case-insensitive. Pattern: // vectool_exclude (lowercase) should match
        /// VECTOOL_EXCLUDE.
        /// </summary>
        [Test]
        public void ExtractMarker_WithLowercaseMarkerKeyword_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"// [vectool:exclude:lowercase_test@Lowercase-Test]
namespace Test { }";
            var filePath = Path.Combine(testRootDirectory, "lowercase_marker.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("lowercase_test", StringCompareShould.IgnoreCase);
        }

        /// <summary>
        /// Test 24: Reason field is case-insensitive in matching. Pattern: VECTOOL_EXCLUDE Generated_By_XSD should
        /// match any case variant.
        /// </summary>
        [Test]
        public void ExtractMarker_WithMixedCaseReason_ReturnsMarkerPattern()
        {
            // Arrange
            var content = @"// [VECTOOL:EXCLUDE:Generated_By_XSD@Mixed-Case]
namespace Test { }";
            var filePath = Path.Combine(testRootDirectory, "mixed_case_reason.cs");
            File.WriteAllText(filePath, content);

            // Act
            var result = extractor.ExtractMarker(filePath);
            LogManager.Flush();

            // Assert
            result.ShouldNotBeNull();
            result!.Reason.ShouldBe("Generated_By_XSD", StringCompareShould.IgnoreCase);
        }
        #endregion
    }
}
